let o = 'hello';
let p = 'owu';
let r = 'com';
let d = 'ua';
let e = 1;
let f = 10;
let g = -999;
let h = 123;
let j = 3.14;
let k = 2.7;
let l = 16;
let m = true;
let n = false;
console.log(o, p, r, d, e, f, g, h, j, k, l, m, n);
let firstName = 'Volodymyr';
let middleName = 'Yosypovych';
let lastName = 'Vrublevskiy';
let lerson = (`${firstName} ${middleName} ${lastName}`);
console.log(lerson);
let a = 100;
console.log(typeof a, a);
let b = '100';
console.log(typeof b, b);
let c = true;
console.log(typeof c, c);
let first_N = prompt('Як вас звати?');
let middle_N = prompt('Як вас по батькові?');
let age = +(prompt('Скільки вам років?'));
console.log(first_N, middle_N, age);
